---
- name: Starting flannel
  command: /bin/true
  notify:
    - start flannel
    - restart docker
    - restart kubelet

- name: start flannel
  service: name=flanneld state=restarted enabled=yes

- name: restart docker
  command: /bin/true
  notify:
    - stop docker
    - start docker

- name: stop docker
  service: name=docker state=stopped

- name: start docker
  service: name=docker state=started

- name: restart kubelet
  service: name=kubelet state=restarted
  when: inventory_hostname in groups['workers']
 
