---
- name: Add repository
  yum_repository:
    name: virt7-docker-common-release
    description: virt7-docker-common-release
    baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
    gpgcheck: no

