---
- name: Installing Kubernetes
  yum: name=kubernetes state=latest

- name: Configuring Kubernetes in master
  template:
    src: "kubernetes_config.j2"
    dest: /etc/kubernetes/config
  notify:
    - Start the appropriate services on master
  when: inventory_hostname in groups['master']

- name: Configuring Kubernetes in workers
  template:
    src: "kubernetes_config.j2"
    dest: /etc/kubernetes/config
  notify:
    - Start the appropriate services on workers
  when: inventory_hostname in groups['workers']

